### ISSUE TITLE
Permission Error Running on the Default Port

### ISSUE THREAD

**Issue by InkDragon** [KrisCris/Palworld-Pal-Editor#18]
**Describe the bug**
Not sure if bug but seems to be a permission error

**To Reproduce**
i have Palworld-Pal-Editor in the same directory as the steam version of the game. Attempting to run the editor results in the following error code with the last line repeating.

`2024-04-08 00:05:38 ←[32;20m[INFO]←[0m Logs written to D:\Games\Steam\steamapps\common\Palworld\logs
2024-04-08 00:05:38 ←[32;20m[INFO]←[0m Config file written to D:\Games\Steam\steamapps\common\Palworld\config.json
2024-04-08 00:05:38 ←[32;20m[INFO]←[0m i18n: en, mode: gui, port: 58080, path: None, password: None, JWT_SECRET_KEY: X2Nvbm5sb3N0
2024-04-08 00:05:38 ←[32;20m[INFO]←[0m Running Palworld-Pal-Editor version: 0.5.1
2024-04-08 00:05:38 ←[32;20m[INFO]←[0m Waiting for backend response...
2024-04-08 00:05:38 ←[32;20m[INFO]←[0m LISTENING ON 127.0.0.1:58080.
Exception in thread Thread-1 (main):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "palworld_pal_editor\webui.py", line 87, in main
  File "waitress\__init__.py", line 13, in serve
  File "waitress\server.py", line 78, in create_server
  File "waitress\server.py", line 243, in __init__
  File "waitress\server.py", line 364, in bind_server_socket
  File "waitress\wasyncore.py", line 395, in bind
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
2024-04-08 00:05:40 ←[32;20m[INFO]←[0m Waiting for backend response...`

**Expected behavior**
For the program to run and show off that beautiful GUI

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox 124.0.2 (I also have chrome installed)
 - Version 22H2, OS Build 19045.4170

**Smartphone (please complete the following information):** Unsure on relevancy
 - Device: Motorola G Stylus 2020
 - OS: Android 11
 - Browser: Firefox 124.2.0

**Comment by KrisCris** [comment]
Hmm, maybe the default port is not available. Do you see a `config.json` file created alongside the `.exe`? Open that and in the port section: `"port": 58080,`, change `58080` to something else, let's say `54321`, save, then restart the tool. 

Or you can randomly pick a port ranged between 10000 - 50000, and see if any of them work for you ;)

**Comment by KrisCris** [comment]
Btw, download the artifacts from this link, which should completely fix the issue: https://github.com/KrisCris/Palworld-Pal-Editor/actions/runs/8601098485

Let me know if it is fixed

**Comment by KrisCris** [comment]
Fixed on 0.6.0

Close as no response.
