### ISSUE TITLE
Palworld 0.3.9 Support

### ISSUE THREAD

**Issue by KrisCris** [KrisCris/Palworld-Pal-Editor#57]
### Discussed in https://github.com/KrisCris/Palworld-Pal-Editor/discussions/54

<div type='discussions-op-text'>

<sup>Originally posted by **Craigyyuna** September 18, 2024</sup>
- loadSave - Error occurred: Undefined

ERROR:palworld_pal_editor.webui:Exception on /api/save/load [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1463, in wsgi_app
  File "flask\app.py", line 872, in full_dispatch_request
  File "flask\app.py", line 870, in full_dispatch_request
  File "flask\app.py", line 855, in dispatch_request
  File "flask_jwt_extended\view_decorators.py", line 170, in decorator
  File "palworld_pal_editor\api\save.py", line 35, in load
  File "palworld_pal_editor\core\save_manager.py", line 298, in open
  File "palworld_save_tools\gvas.py", line 131, in read
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 399, in property
  File "palworld_save_tools\archive.py", line 515, in struct
  File "palworld_save_tools\archive.py", line 542, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 477, in property
  File "palworld_save_tools\archive.py", line 499, in prop_value
  File "palworld_save_tools\archive.py", line 542, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 396, in property
  File "palworld_save_tools\rawdata\character.py", line 13, in decode
  File "palworld_save_tools\rawdata\character.py", line 22, in decode_bytes
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 399, in property
  File "palworld_save_tools\archive.py", line 515, in struct
  File "palworld_save_tools\archive.py", line 542, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 493, in property
Exception: Unknown type: ByteProperty (.SaveParameter.Level)</div>

**Comment by KrisCris** [comment]
I can try to fix this issue if you could give me a gamesave. @Craigyyuna

**Comment by KrisCris** [comment]
We will need to wait for this dependency to get an update: https://github.com/cheahjs/palworld-save-tools/issues/187

**Comment by Parzival-1337** [comment]
I ran into the exact same problem 

ERROR:palworld_pal_editor.webui:Exception on /api/save/load [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1463, in wsgi_app
  File "flask\app.py", line 872, in full_dispatch_request
  File "flask\app.py", line 870, in full_dispatch_request
  File "flask\app.py", line 855, in dispatch_request
  File "flask_jwt_extended\view_decorators.py", line 170, in decorator
  File "palworld_pal_editor\api\save.py", line 35, in load
  File "palworld_pal_editor\core\save_manager.py", line 298, in open
  File "palworld_save_tools\gvas.py", line 131, in read
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 399, in property
  File "palworld_save_tools\archive.py", line 515, in struct
  File "palworld_save_tools\archive.py", line 542, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 477, in property
  File "palworld_save_tools\archive.py", line 499, in prop_value
  File "palworld_save_tools\archive.py", line 542, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 396, in property
  File "palworld_save_tools\rawdata\character.py", line 13, in decode
  File "palworld_save_tools\rawdata\character.py", line 22, in decode_bytes
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 399, in property
  File "palworld_save_tools\archive.py", line 515, in struct
  File "palworld_save_tools\archive.py", line 542, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 493, in property
Exception: Unknown type: ByteProperty (.SaveParameter.Level)

- loadSave - Error occured: undefined

**Comment by titotito9799** [comment]
I'm having a similar problem..

2024-09-19 01:30:17 [32;20m[INFO][0m Opening D:\steam\steamapps\common\PalServer\Pal\Saved\SaveGames\0\53A69517449D39283D5921BF5744D8F5\Level.sav
2024-09-19 01:30:17 [32;20m[INFO][0m Decompressing sav
2024-09-19 01:30:17 [32;20m[INFO][0m Reading GVAS file
ERROR:palworld_pal_editor.webui:Exception on /api/save/load [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1463, in wsgi_app
  File "flask\app.py", line 872, in full_dispatch_request
  File "flask\app.py", line 870, in full_dispatch_request
  File "flask\app.py", line 855, in dispatch_request
  File "flask_jwt_extended\view_decorators.py", line 170, in decorator
  File "palworld_pal_editor\api\save.py", line 35, in load
  File "palworld_pal_editor\core\save_manager.py", line 298, in open
  File "palworld_save_tools\gvas.py", line 131, in read
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 399, in property
  File "palworld_save_tools\archive.py", line 515, in struct
  File "palworld_save_tools\archive.py", line 542, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 477, in property
  File "palworld_save_tools\archive.py", line 499, in prop_value
  File "palworld_save_tools\archive.py", line 542, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 396, in property
  File "palworld_save_tools\rawdata\character.py", line 13, in decode
  File "palworld_save_tools\rawdata\character.py", line 22, in decode_bytes
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 399, in property
  File "palworld_save_tools\archive.py", line 515, in struct
  File "palworld_save_tools\archive.py", line 542, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 493, in property
Exception: Unknown type: ByteProperty (.SaveParameter.Level)

**Comment by Parzival-1337** [comment]
> У меня похожая проблема..
> 
> 2024-09-19 01:30:17 �[32;20m[INFO]�[0m Открытие D:\steam\steamapps\common\PalServer\Pal\Saved\SaveGames\0\53A69517449D39283D5921BF5744D8F5\Level.sav 2024-09-19 01:30:17 �[32 ;20m[INFO]�[0m Распаковка sav 2024-09-19 01:30:17 �[32;20m[INFO]�[0m Чтение файла GVAS ОШИБКА:palworld_pal_editor.webui:Исключение в /api/save/load [POST] Traceback (большинство последний вызов): Файл "flask\app.py", строка 1463, в wsgi_app Файл "flask\app.py", строка 872, в full_dispatch_request Файл "flask\app.py", строка 870, в full_dispatch_request Файл "flask\app.py", строка 855, в dispatch_request Файл "flask_jwt_extended\view_decorators.py", строка 170, в decorator Файл "palworld_pal_editor\api\save.py", строка 35, в load Файл "palworld_pal_editor\core\save_manager.py", строка 298, в open Файл "palworld_save_tools\gvas.py", строка 131, в read Файл "palworld_save_tools\archive.py", строка 386, в properties_until_end Файл "palworld_save_tools\archive.py", строка 399, в свойстве Файл "palworld_save_tools\archive.py", строка 515, в структуре Файл "palworld_save_tools\archive.py", строка 542, в struct_value Файл "palworld_save_tools\archive.py", строка 386, в properties_until_end Файл "palworld_save_tools\archive.py", строка 477, в свойстве Файл "palworld_save_tools\archive.py", строка 499, в prop_value Файл "palworld_save_tools\archive.py", строка 542, в struct_value Файл "palworld_save_tools\archive.py", строка 386, в properties_until_end Файл "palworld_save_tools\archive.py", строка 396, в свойстве Файл "palworld_save_tools\rawdata\character.py", строка 13, в decode Файл "palworld_save_tools\rawdata\character.py", строка 22, в decode_bytes Файл "palworld_save_tools\archive.py", строка 386, в properties_until_end Файл "palworld_save_tools\archive.py", строка 399, в property Файл "palworld_save_tools\archive.py", строка 515, в struct Файл "palworld_save_tools\archive.py", строка 542, в struct_value Файл "palworld_save_tools\archive.py", строка 386, в properties_until_end Файл "palworld_save_tools\archive.py", строка 493, в property Исключение: Неизвестный тип: ByteProperty (.SaveParameter.Level)

The problem is in the new version of the game (sorted out). We need to wait until the new variable is updated

**Comment by cnrenil** [comment]
If anyone want to use this editor, the [cheahjs/palworld-save-tools/issues/187#issuecomment-2359196290](https://github.com/cheahjs/palworld-save-tools/issues/187#issuecomment-2359196290) tools could be used to replace original tool. I tested and build a .exe program. some information cannot be displayed but could make modification and save.

If anyone want to build a .exe by yourself, you can execute these step by step.

1. First clone this repo(use git clone).
2. Install nodejs and python 312(i used and tested)
3. Open setup and run.ps1(maybe) use notepad.exe and delete venv environment. execute this ps1.
4. Close the program(because the save tools have not be replaced).
5. cd C:\python312\xxxxxx\site-packages.(sorry i forgoted), find the pal save tools(not .dist-info). delete all files in it, and download the zip in [cheahjs/palworld-save-tools/issues/187#issuecomment-2359196290](https://github.com/cheahjs/palworld-save-tools/issues/187#issuecomment-2359196290).
6. unzip and place these files in zip to the path  in 5th step.
7. now you can run the build exe ps1(dont forgot delete venv use notepad)
8. locate dists/xxx.exe, now you got it.



Finally, This comment is full of grammar errors and various other questions, please understand that I am not a native English speaker. And this comment is edited on the mobile phone, the computer can not open temporarily due to some problems, some paths and files are difficult to speak correctly.

**Comment by RPMC-Marco** [comment]
SUGGESTION: would switching dependency to https://github.com/deafdudecomputers/PalWorldSaveTools be an easy thing?
From its looks, this has been updated and maintained much more.

**Comment by KrisCris** [comment]
https://github.com/KrisCris/Palworld-Pal-Editor/releases/tag/v0.10.0

Updates available!! Please let me know if there are bugs to be fixed!

**Comment by KrisCris** [comment]
https://github.com/KrisCris/Palworld-Pal-Editor/actions/runs/11270288341

More fixes for soul/condenser ranks, adding pals, and so on

**Comment by gmd1999** [comment]
>>> 2024-12-22 23:22:13 [INFO] LISTENING ON 127.0.0.1:58080.
2024-12-22 23:22:14 [INFO] Backend ready, launching GUI...
2024-12-22 23:22:14 [INFO] If GUI doesn't work for you, check out this post: https://github.com/KrisCris/Palworld-Pal-Editor/issues/4
2024-12-22 23:22:21 [INFO] Opening C:\Users\Mingda Gao\AppData\Local\Pal\Saved\SaveGames\76561198291595293\47877C8A473EA2EAF2CD529CF6582C00\Level.sav
2024-12-22 23:22:21 [INFO] Decompressing sav
2024-12-22 23:22:21 [INFO] Reading GVAS file
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: Unknown base camp module type EPalBaseCampModuleType::ItemStackInfo, skipping
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: Unknown base camp module type EPalBaseCampModuleType::ItemStackInfo, skipping
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: Unknown base camp module type EPalBaseCampModuleType::ItemStackInfo, skipping
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: Unknown base camp module type EPalBaseCampModuleType::ItemStackInfo, skipping
ERROR:palworld_pal_editor.webui:Exception on /api/save/load [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1463, in wsgi_app
  File "flask\app.py", line 872, in full_dispatch_request
  File "flask\app.py", line 870, in full_dispatch_request
  File "flask\app.py", line 855, in dispatch_request
  File "flask_jwt_extended\view_decorators.py", line 170, in decorator
  File "palworld_pal_editor\api\save.py", line 35, in load
  File "palworld_pal_editor\core\save_manager.py", line 298, in open
  File "palworld_save_tools\gvas.py", line 131, in read
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 399, in property
  File "palworld_save_tools\archive.py", line 534, in struct
  File "palworld_save_tools\archive.py", line 561, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 396, in property
  File "palworld_save_tools\rawdata\group.py", line 17, in decode
  File "palworld_save_tools\rawdata\group.py", line 77, in decode_bytes
Exception: Warning: EOF not reached

Any ideas?
