### ISSUE TITLE
[BUG] Character lacking nickname

### ISSUE THREAD

**Issue by samuel-yang7** [KrisCris/Palworld-Pal-Editor#69]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).
- [X] I have checked for both game and editor updates, and understand that issues on older versions may not be resolved.

### Bug Report Description

i tried to edit a dedicated server save, but only my profile isn't available to edit, all my friend's profile is avaliable. it says:"fetchPlayerPal - Error occured: undefined"
![image](https://github.com/user-attachments/assets/1f85b8f8-ae7d-46e1-8aff-a8b726cd3e22)

### Expected Behaviour

i should be able to edit all profiles

### Editor Version

0.10.1

### Game Version

0.3.10..61184

### Logs

ERROR:palworld_pal_editor.webui:Exception on /api/pal/paldata [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1463, in wsgi_app
  File "flask\app.py", line 872, in full_dispatch_request
  File "flask\app.py", line 870, in full_dispatch_request
  File "flask\app.py", line 855, in dispatch_request
  File "flask_jwt_extended\view_decorators.py", line 170, in decorator
  File "palworld_pal_editor\api\pal.py", line 75, in paldata
  File "palworld_pal_editor\utils\util.py", line 13, in reply
  File "flask\json\__init__.py", line 170, in jsonify
  File "flask\json\provider.py", line 214, in response
  File "flask\json\provider.py", line 179, in dumps
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 200, in encode
  File "json\encoder.py", line 258, in iterencode
  File "flask\json\provider.py", line 121, in _default
TypeError: Object of type UUID is not JSON serializable

### Your Game Save

[Level.zip](https://github.com/user-attachments/files/17735568/Level.zip)

**Comment by samuel-yang7** [comment]
I kinda found out the reason, is that my profile dont have a nickname so it cant be detected as a legal player. is there any method to solve this?

**Comment by KrisCris** [comment]
> I kinda found out the reason, is that my profile dont have a nickname so it cant be detected as a legal player. is there any method to solve this?

I haven't played the game for a while, so now the game no longer requires a character name to play? Was your Steam profile name being automatically used?

I will work on a fix later.

**Comment by samuel-yang7** [comment]
> > I kinda found out the reason, is that my profile dont have a nickname so it cant be detected as a legal player. is there any method to solve this?
> 
> I haven't played the game for a while, so now the game no longer requires a character name to play? Was your Steam profile name being automatically used?
> 
> I will work on a fix later.

yeah i fixed it. its just me having a blank name, changed it ingame. thanks a lot for this editor
