### ISSUE TITLE
[BUG] Cannot load my save files

### ISSUE THREAD

**Issue by gmd1999** [KrisCris/Palworld-Pal-Editor#74]
### Please confirm

- [X] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).
- [X] I have checked for both game and editor updates, and understand that issues on older versions may not be resolved.

### Bug Report Description

The editor cannot load my save files. It keeps showing "- loadSave - Error occured: undefined" "Exception: Warning: EOF not reached"

I am not sure if this problem is related to the big update of this game or not. 

### Expected Behaviour

Should be able to load the save files

### Editor Version

0.10.1

### Game Version

0.4.11

### Logs

2024-12-23 01:14:09 [INFO] Opening C:\Users\Mingda Gao\AppData\Local\Pal\Saved\SaveGames\76561198291595293\47877C8A473EA2EAF2CD529CF6582C00\Level.sav
2024-12-23 01:14:09 [INFO] Decompressing sav
2024-12-23 01:14:09 [INFO] Reading GVAS file
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: Unknown base camp module type EPalBaseCampModuleType::ItemStackInfo, skipping
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: Unknown base camp module type EPalBaseCampModuleType::ItemStackInfo, skipping
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: Unknown base camp module type EPalBaseCampModuleType::ItemStackInfo, skipping
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: Unknown base camp module type EPalBaseCampModuleType::ItemStackInfo, skipping
ERROR:palworld_pal_editor.webui:Exception on /api/save/load [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1463, in wsgi_app
  File "flask\app.py", line 872, in full_dispatch_request
  File "flask\app.py", line 870, in full_dispatch_request
  File "flask\app.py", line 855, in dispatch_request
  File "flask_jwt_extended\view_decorators.py", line 170, in decorator
  File "palworld_pal_editor\api\save.py", line 35, in load
  File "palworld_pal_editor\core\save_manager.py", line 298, in open
  File "palworld_save_tools\gvas.py", line 131, in read
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 399, in property
  File "palworld_save_tools\archive.py", line 534, in struct
  File "palworld_save_tools\archive.py", line 561, in struct_value
  File "palworld_save_tools\archive.py", line 386, in properties_until_end
  File "palworld_save_tools\archive.py", line 396, in property
  File "palworld_save_tools\rawdata\group.py", line 17, in decode
  File "palworld_save_tools\rawdata\group.py", line 77, in decode_bytes
Exception: Warning: EOF not reached

**Comment by gmd1999** [comment]
[Level.zip](https://github.com/user-attachments/files/18226388/Level.zip)
Here's my save file

**Comment by gmd1999** [comment]
The log is attached:

2024-12-23 01:08:04 [INFO] Logs written to D:\Game\Cheat\ALI213-Palworld.Early.Access.Plus.46.Trainer-FLiNG\Editor\logs
2024-12-23 01:08:04 [INFO] Config file written to D:\Game\Cheat\ALI213-Palworld.Early.Access.Plus.46.Trainer-FLiNG\Editor\config.json
2024-12-23 01:08:04 [INFO] i18n: zh-CN, mode: gui, port: 58080, path: C:\Users\Mingda Gao\AppData\Local\Pal\Saved\SaveGames\76561198291595293\47877C8A473EA2EAF2CD529CF6582C00, password: None, JWT_SECRET_KEY: X2Nvbm5sb3N0
2024-12-23 01:08:04 [INFO] Running Palworld-Pal-Editor version: 0.10.1
2024-12-23 01:08:04 [INFO] Palworld Pal Editor v0.10.1, made by _connlost with ❤.
2024-12-23 01:08:04 [INFO] Waiting for backend response...
2024-12-23 01:08:04 [INFO] LISTENING ON 127.0.0.1:58080.
2024-12-23 01:08:04 [INFO] Backend ready, launching GUI...
2024-12-23 01:08:04 [INFO] If GUI doesn't work for you, check out this post: https://github.com/KrisCris/Palworld-Pal-Editor/issues/4
2024-12-23 01:11:29 [INFO] Opening C:\Users\Mingda Gao\AppData\Local\Pal\Saved\SaveGames\76561198291595293\47877C8A473EA2EAF2CD529CF6582C00\Level.sav
2024-12-23 01:11:29 [INFO] Decompressing sav
2024-12-23 01:11:30 [INFO] Reading GVAS file
2024-12-23 01:14:09 [INFO] Opening C:\Users\Mingda Gao\AppData\Local\Pal\Saved\SaveGames\76561198291595293\47877C8A473EA2EAF2CD529CF6582C00\Level.sav
2024-12-23 01:14:09 [INFO] Decompressing sav
2024-12-23 01:14:09 [INFO] Reading GVAS file

**Comment by MartiniJac** [comment]
I think it's possible that the game version has been updated with some new features, but the tools haven't been updated yet, so I can't read the save files.

**Comment by dedren** [comment]
Exact same issue here. Do you need another save or something else?

**Comment by Senaratheumbreon** [comment]
its because the editor hasnt been updated with the new things that palworld added as of midnight japan time 12/23 so the new code is not in the editor yet

**Comment by KrisCris** [comment]
> [Level.zip](https://github.com/user-attachments/files/18226388/Level.zip) Here's my save file

I need the entire save folder to be able to load your gamesave.

**Comment by NinomaeTakonis** [comment]
> > [Level.zip](https://github.com/user-attachments/files/18226388/Level.zip) Here's my save file
> 
> I need the entire save folder to be able to load your gamesave.

Can't attach the whole folder as its too big, so hopefully this is okay. Hope this helps!
https://gofile.io/d/DwYsa0

**Comment by KrisCris** [comment]
Thanks, I made [an experimental build](https://github.com/KrisCris/Palworld-Pal-Editor/actions/runs/12481727934/artifacts/2359217591) that hopefully addresses the loading issue, please backup your game save and give it a try!

**Comment by Senaratheumbreon** [comment]
it works but missing the data for the new pals, skills and attacks

**Comment by Rocky123e** [comment]
When I save the edits it doesnet work

**Comment by oseam2036** [comment]
작동하지 않습니다

**Comment by oseam2036** [comment]
Today, I reinstalled Palworld Pal Editor and put in the saved file, but it doesn't work. Dear creator

**Comment by KrisCris** [comment]
To save my sanity, everyone please post your editor version number, and verify that you are running the latest build.

**Comment by Rocky123e** [comment]
Ok I’ll do it when I get back home

**Comment by ybother123** [comment]
Video included
https://youtu.be/2QJBFfIn4mM

12-23-24 Update Broke the Software

Palworld Version: 0.4.11.64664



Error from the GUI fix version of the software

Happens after you click load save file. Unable to open.
`Error from gui fix exe
ERROR:palworld_pal_editor.webui:Exception on /api/save/load [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1463, in wsgi_app
  File "flask\app.py", line 872, in full_dispatch_request
  File "flask\app.py", line 870, in full_dispatch_request
  File "flask\app.py", line 855, in dispatch_request
  File "flask_jwt_extended\view_decorators.py", line 170, in decorator
  File "palworld_pal_editor\api\save.py", line 32, in load
  File "palworld_pal_editor\core\save_manager.py", line 296, in open
  File "palworld_save_tools\gvas.py", line 131, in read
  File "palworld_save_tools\archive.py", line 291, in properties_until_end
  File "palworld_save_tools\archive.py", line 304, in property
  File "palworld_save_tools\archive.py", line 415, in struct
  File "palworld_save_tools\archive.py", line 442, in struct_value
  File "palworld_save_tools\archive.py", line 291, in properties_until_end
  File "palworld_save_tools\archive.py", line 377, in property
  File "palworld_save_tools\archive.py", line 399, in prop_value
  File "palworld_save_tools\archive.py", line 442, in struct_value
  File "palworld_save_tools\archive.py", line 291, in properties_until_end
  File "palworld_save_tools\archive.py", line 301, in property
  File "palworld_save_tools\rawdata\character.py", line 13, in decode
  File "palworld_save_tools\rawdata\character.py", line 22, in decode_bytes
  File "palworld_save_tools\archive.py", line 291, in properties_until_end
  File "palworld_save_tools\archive.py", line 304, in property
  File "palworld_save_tools\archive.py", line 415, in struct
  File "palworld_save_tools\archive.py", line 442, in struct_value
  File "palworld_save_tools\archive.py", line 291, in properties_until_end
  File "palworld_save_tools\archive.py", line 393, in property
Exception: Unknown type: ByteProperty (.SaveParameter.Level)`

**Comment by NinomaeTakonis** [comment]
I tried the experimental version and it seems to load the save fine without error. The editor is just missing the new additions, such as level 60, 60% statue of power boosts, new skills and passives, predators and work suitability upgrades.

Obviously those additions will take time, so no worries. At least the experimental version is usable in the meantime.

**Comment by fly9702** [comment]
> [감사합니다. 로드 문제를 처리하는 실험용 빌드를](https://github.com/KrisCris/Palworld-Pal-Editor/actions/runs/12481727934/artifacts/2359217591) 생성하고 , 게임 저장 데이터를 백업하고 계속해서 살펴보세요!

이 버전으로 실행했더니 정상적으로 잘 작동합니다. 감사합니다

**Comment by KrisCris** [comment]
fixed
